export enum AuditEntity {
  TRANSACTION = 'TRANSACTION',
  ACCOUNT = 'ACCOUNT',
  CATEGORY = 'CATEGORY',
  BUDGET = 'BUDGET',
  GOAL = 'GOAL',
  USER = 'USER',
  NOTIFICATION = 'NOTIFICATION',
  AI_CONFIG = 'AI_CONFIG',
  RECURRING_TRANSACTION = 'RECURRING_TRANSACTION',
}
