export enum AuditEntity {
  TRANSACTION = 'TRANSACTION',
  ACCOUNT = 'ACCOUNT',
  BUDGET = 'BUDGET',
  GOAL = 'GOAL',
  CATEGORY = 'CATEGORY',
  USER = 'USER',
  RECURRING_TRANSACTION = 'RECURRING_TRANSACTION',
}
